name: Setup Next.js Structure

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Create Next.js structure
        run: |
          # Create directories
          mkdir -p src/app
          
          # Create page.tsx
          echo 'export default function Home() {
            return (
              <main className="flex min-h-screen flex-col items-center justify-between p-24">
                <h1>Welcome to Stuffix</h1>
                <p>Your secure and modern web application</p>
              </main>
            );
          }' > src/app/page.tsx
          
          # Create layout.tsx
          echo 'import "./globals.css";
          
          export const metadata = {
            title: "Stuffix",
            description: "Your secure and modern web application",
          };
          
          export default function RootLayout({
            children,
          }: {
            children: React.ReactNode;
          }) {
            return (
              <html lang="en">
                <body>{children}</body>
              </html>
            );
          }' > src/app/layout.tsx
          
          # Create globals.css
          echo '@tailwind base;
          @tailwind components;
          @tailwind utilities;
          
          :root {
            --foreground-rgb: 0, 0, 0;
            --background-rgb: 255, 255, 255;
          }
          
          body {
            color: rgb(var(--foreground-rgb));
            background: rgb(var(--background-rgb));
          }' > src/app/globals.css
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Setup Next.js structure"
          git push
